### ISSUE TITLE
Practica3 Interfaz Gráfica con interactividad 

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-topicos-avanzados-4us#1]
[practicalll.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-topicos-avanzados-4us/files/10772437/practicalll.pdf)

**Comment by ToniDepp** [comment]
**Portada:** 20% Aunque carece de formato es una portada que cumple con lo que se pide.
**Procedimiento:** 17% Su código requería de una breve explicación, por el hecho de que como funcionaban sus procesos dentro de la compilación de su aplicación. 
**Figuras ilustraciones y fotografías:** 25% Muy completo en cuanto sus imágenes.
**Resultados y conclusiones:** 17% No dejan tan claro que aprendieron, solo le dan vueltas a lo que intentan decir y las faltas de ortografía están presentes.

Calificación: 79%/100% = 15.8/20

Calificado por el Equipo 2

**Comment by josealfredo79** [comment]
bien hecho y revisado
